### ISSUE TITLE
README should document the header storage location and how to change it

### ISSUE THREAD

**Issue by rt121212121** [bitcoin-sv/block-headers-client#11]
I had to use process explorer on Windows to locate where the headers were stored (something like `AppData\Local\Temp\jcl`). It would be good to be able to specify the location the data goes, and this is probably already possible but would benefit from mentioning in the README, which makes it more easily deletable in the regtest cases.

**Comment by Danconnolly** [comment]
You've made several useful comments here. It would be great if you went ahead and submitted a pull request :-)

**Comment by rt121212121** [comment]
@jadwahab We have this on our task list, but we've been asked to focus on critical ESV tasks to our 1.4.0 release which is a more than reasonable request. Jad wanted this handed off to the liteclient team. Jad, did you have someone in mind who could do this?

**Comment by Danconnolly** [comment]
I've already asked the Header SV team to look at these. Taking this to email.

**Comment by Fletch153** [comment]
I've updated the README with the default location of the app database and logged internally to provide functionality so this can be overridden using an env variable, as currently, it needs to be specified within the code.
