### ISSUE TITLE
Client stuck on requesting block 556000

### ISSUE THREAD

**Issue by jdr377** [bitcoin-sv/block-headers-client#13]
I've had two issues with block requests so far:

- Client would sometimes get stuck on a recent block on BSV chain but won't progress (happens when system is offline for some time)
- Client will fail to request blocks beyond 556000, likely due to it being a block involving a network fork

My only solution thus far is to completely wipe the image and re-install.

![image](https://user-images.githubusercontent.com/69904251/169735455-9b701770-b0a3-41a4-a849-b25e8c853bd0.png)

**Comment by Fletch153** [comment]
This is an issue where the peer is not connected to any responsive BSV nodes, the solution is to increase the maxPeers. Major improvements to this have been made in release 2.0.2 which should improve peer discovery, and prevent connecting to dead / bch nodes.
