### ISSUE TITLE
Would be nice to have websockets integrated

### ISSUE THREAD

**Issue by iangregsondev** [bitcoin-sv/block-headers-client#14]
Hi,

It would be nice to have websockets integrated so that external applications can subscribe and know ahead of time where the block header client is.

i.e. like zeromq for bitcoind - but just for the block-headers-client.

Not sure if this is planned.

Although it would be nice to be able to opt-in to subscribe to new block found, errors received, etc.

Best regards

Ian

**Comment by Fletch153** [comment]
Raised internally, thanks.

**Comment by iangregsondev** [comment]
Thanks, @Fletch153 , I found that you have modularised them now, and there is something called CORE that exists, so I have been trying to wrap this, but it failed! The websockets isn't that important for me now if the modules work as I can just push onto a rabbitmq queue - which is what I wanted to do anyway.

Thanks for the reply anyway.

[DELETED by Daniel. Please dont link issues unless there is a meaning to that link]

**Comment by Danconnolly** [comment]
Opening this back up. Maybe someone wants to contribute this?

@iangregsondev would you expand on what it is you think would be useful? Define some requirements?

**Comment by iangregsondev** [comment]
Hi,

There are internal events that happen inside of the headers clients, it would be nice to be able to raise these also via websockets so that we have the option to listen. Think ZeroMQ with bitcoind, but, not a great idea to use ZeroMQ - in my opinion.

Although after I raised this issue, I noticed you can also use "CORE" (So internally, I can run the headers client as a library) - so you can write your own wrapper around the headers client. This was a great idea; I have some kotlin experience, so I decided to write my own wrapper and push the events onto a queue which is essentially what I wanted to do with the websocket integration.

Unfortunately, I found issues. It's raised in another issue.


Thanks for re-opening it @Danconnolly , I think it is still beneficial if somebody doesn't have java/kotlin experience to develop the wrapper, but if the idea of the wrapper worked - this would be my preferred way of doing it.

**Comment by Danconnolly** [comment]
Yes I saw the other issue, but it's not directly related to this issue, so please dont link them.

**Comment by iangregsondev** [comment]
Oops, sorry, my bad for linking it, I was only stating that the CORE fixes this.

To summarise, the requirements would be that the internal events that are raised in the code (there are only a few) should be allowed to be pushed out via websockets.

This gives some great insight (without polling) of where (which height for example) the headers client is.
