### ISSUE TITLE
Failed Installation 

### ISSUE THREAD

**Issue by carrretero** [bitcoin-sv/block-headers-client#6]
I am trying to install headersSV client on Linux Mint but upon running

./gradlew clean build

i get the following notice:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'headerSV'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download jib-gradle-plugin-3.1.4.jar (gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:3.1.4)
      > Could not get resource 'https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/3.1.4/jib-gradle-plugin-3.1.4.jar'.
         > Could not GET 'https://plugins-artifacts.gradle.org/gradle.plugin.com.google.cloud.tools/jib-gradle-plugin/3.1.4/abc1dacd0d469fec7550f5497fe32aa0103e5d2a549683d3ef43c31fb2423732/jib-gradle-plugin-3.1.4.jar'.
            > Remote host terminated the handshake

Could you please assist me with this? I would love to try it out.

Another thing, maybe not an issue, but i have installed the latest version of gradle on the system (7.4.2), then attempted to build, and it went to downloading an older version of gradle first (6.5.1) and failed several times, maybe due to a bad connection, so i downloaded that version manually, placed the zip in the corresponding directory and then the build process would actually start, but throwing the error described above.

**Comment by Fletch153** [comment]
Hi @carrretero, you should be able to run the wrapper without installing Gradle. The error attached looks to be connection-related. Could you confirm whether you resolved this?

**Comment by carrretero** [comment]
It was indeed connection related but now i ran into another issue, the build would fail with the following output:

> Task :javadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/home/carrretero/headerSV/build/tmp/javadoc/javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
11 actionable tasks: 11 executed

**Comment by Fletch153** [comment]
Your machine requires javadoc in order to build from source. The solution to this is to install a JDK which contains javadoc
.

**Comment by carrretero** [comment]
I have wiped all openjdk packages and reinstalled the default-jdk package. 
Now it works, and the 2.0.0 version loads all the block headers. 

Thank you.
