### ISSUE TITLE
README unnecessarily implies it gradle should be downloaded

### ISSUE THREAD

**Issue by rt121212121** [bitcoin-sv/block-headers-client#7]
The instructions infer you should download gradle, but running gradlew downloads and runs gradle. It would be good if a note that gradle is downloaded and run automatically (even if only on windows)  could prefix the reference to the gradle download.

```
C:\Data\Git\block-headers-client>gradlew clean build
Downloading https://services.gradle.org/distributions/gradle-6.5.1-bin.zip
.......
```

**Comment by Fletch153** [comment]
Improvements have been made to the README files
