### ISSUE TITLE
README could have a better Java download link (or links)

### ISSUE THREAD

**Issue by rt121212121** [bitcoin-sv/block-headers-client#8]
The instructions point you at some abstract documentation about installing java, it would be good if it instead had a link to an actual openjdk download link before the installation help link it currently has (it took me about 8 clicks to get to a jdk download link then I got an oracle login). This link is where ended up after a google: https://jdk.java.net/18/

**Comment by Danconnolly** [comment]
I dont completely agree with this. For the following reasons:

* Docker should be the recommended method for using this - we have an outstanding task to update the documentation to refer to the docker image along with instructions for using it
* Installing Java is a whole topic in itself and I dont think we should go into it in this repository. There are so many different ways to install it, each dependent on the platform, I'm not sure we should pick one method over another.
* I know that licensing on the Oracle Java versions has changed in the last few years but I have not looked at what those changes are and I have no intention of doing that either. I just know it can be an issue.

**Comment by Fletch153** [comment]
Some improvements have been made to the documentation, outlining prerequisites, but ultimately relies on the user being able to install the jdk independently.
